// Convert 1.Y.Z components to their individual counterpart
module.exports = {
  Accordion: {
    isChild: true,
    package: 'core-expand-collapse',
    combineWith: ['ExpandCollapse']
  },
  Box: 'core-box',
  Button: 'core-button',
  ButtonLink: 'core-button-link',
  Card: 'core-card',
  Checkbox: 'core-checkbox',
  ChevronLink: 'core-chevron-link',
  DecorativeIcon: 'core-decorative-icon',
  DimpleDivider: 'core-dimple-divider',
  DisplayHeading: 'core-display-heading',
  ExpandCollapse: {
    isChild: true,
    package: 'core-expand-collapse',
    combineWith: ['Accordion']
  },
  FlexGrid: 'core-flex-grid',
  HairlineDivider: 'core-hairline-divider',
  Heading: 'core-heading',
  Image: 'core-image',
  Input: 'core-input',
  InputFeedback: 'core-input-feedback',
  Link: 'core-link',
  Notification: 'core-notification',
  OrderedList: 'core-ordered-list',
  Paragraph: 'core-paragraph',
  Radio: 'core-radio',
  Responsive: 'core-responsive',
  Select: 'core-select',
  SelectorCounter: 'core-selector-counter',
  Small: 'core-small',
  Spinner: 'core-spinner',
  StandaloneIcon: 'core-standalone-icon',
  StepTracker: 'core-step-tracker',
  Strong: 'core-strong',
  Text: 'core-text',
  TextArea: 'core-text-area',
  Tooltip: 'core-tooltip',
  UnorderedList: 'core-unordered-list',
  WaveDivider: 'core-wave-divider',
}